# Generated by Django 5.1.3 on 2024-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "conference_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authors", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("abstract", models.TextField(blank=True, null=True)),
                ("paper_file", models.FileField(upload_to="research_papers/")),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
            ],
            options={"ordering": ["-date"],},
        ),
    ]
