# Generated by Django 5.1.3 on 2024-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchpaper",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
