# Generated by Django 5.1.3 on 2024-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_link_projects_github_projects_live"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
