# Generated by Django 5.1.3 on 2024-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="publication_date",
            field=models.IntegerField(help_text="Date when the book was published"),
        ),
    ]
