# Generated by Django 5.1.3 on 2024-12-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_books_publication_date"),
    ]

    operations = [
        migrations.AlterModelOptions(name="books", options={},),
    ]
