# Generated by Django 5.1.3 on 2024-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="logo/"),
        ),
    ]
